<?php

$ans = array(
    "0"=>"",
    "1"=>"",
    "2"=>"sunrisedhaba",
    "3"=>"insight",
    "4"=>"victormenezes",
    "5"=>"kanwalrekhi",
    "6"=>"550acres",
    "7"=>"nandannilekani",
    "8"=>"bakuldesai",
    "9"=>"hostel14",
    "10"=>"bharatdesai",
    "11"=>"girishgaitonde",
    "12"=>"pranavmistry",
    "13"=>"ma105",
    "14"=>"sameer",
    "15"=>"deepakpatil",
    "16"=>"centrefortechnologyalternativesforruralareas",
    "17"=>"mansoorkhan",
    "18"=>"hostelalumniteamstewardship",
    "19"=>"manoharparrikar",
    "20"=>"arunnetravali",
    "21"=>"kshitijgarden",
    "22"=>"reddymadecement",
    "23"=>"sunrisedhaba",
    "24"=>"ajitranade",
    "25"=>"madhouse",
    "26"=>"ananta",
    "27"=>"jairamramesh",
    "28"=>"aerospace",
    "29"=>"iyengarashvin",
    "30"=>"maingatessaarchitects",
    "31"=>"madanmohanrao",
	"32"=>"",
	"33"=>"sarcasm");
    

?>